# Request is empty
---
uint16 status_value
bool ready_to_switch_on
bool switched_on
bool operation_enabled
bool fault
bool voltage_enabled
bool quick_stop
bool switch_on_disabled
bool warning
bool drive_profile_operation_ready
bool remote
bool target_reached
bool internal_limit_active
